### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by d-koudz** [INFO526-DataViz/project-final-Chart-Champions#1]
The following is the peer review of the project proposal by [name of team completing peer review]. The team members that participated in this review are 

- Ansh Kumar Dev - @Anshkumardev

- Rahul Bangad - @rahulbangad98

- Swati Das - @Swati09Das

- Deema Albluwi - @Deec0dez

- Shakir Ahmed - @Shakir0585

- Describe the goal of the project.

To develop a Shiny app that generates constellation maps integrating interactive elements, implementing both computational and visualization techniques.

- Describe the data used or collected.

The datasets are in format *.geojson and *.gpkg format. They are categorised into five sections: Asterisms, Constellations,DSOs (Deep-Sky Objects), Stars, and the Milky Way. Each osf them then is divided into several subfiles.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.

They will develop a Shiny app that will generate interactive constellation maps. This will also prioritizes accessibility and personalization of these maps. The users will input specific geographic locations, the app will then provide personalized, contextually relevant constellation maps for each users. They are gonna create maps using sf object and sperical geoms using s2. Then add scatterplot of the constellation on top of the prepared spherical geom. They will create a workflow that provided size, theme and customization of maps. Finally they are gonna test different parameters to identify edge cases. And after working on feedback, they gonna deploy the app.

- Is there anything that is unclear from the proposal?

Nope!

- Provide constructive feedback on how the team might be able to improve their project.

Early user testing, perhaps in Week 5 or 6, could provide valuable insights before the final refinement phase.

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.

We are excited about the integration of computational techniques with interactive visualization to create a Shiny app that will transform astronomical data into personalized and accessible constellation maps for users of varying backgrounds.

- Provide constructive feedback on any issues with file and/or code organization.

The repo is well-organized, with clear separation of code, data, and documentation.

- (Optional) Any further comments or feedback?

There is a great commitment to accessibility in the project, but the proposal does not specify how the app will be made accessible to users with disabilities. It would be advantageous to outline how the team plans to adhere to Web Content Accessibility Guidelines (WCAG) or other accessibility standards. 
Best of luck!

**Comment by meganhokama** [comment]
Thank you so much for the constructive feedback, we have addressed the comments and look forward to seeing your project as well!
