### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by hari1016** [INFO526-DataViz/project-final-Chart-Champions#2]
The following is the peer review of the project proposal by Graph Gurus. The team members that participated in this review are 

- Akrant Varshney - @AkrantVarshney
- Hariharan Ramesh - @hari1016
- Swetha Siripurapu - @SwethaSiripurapuu
- Maria Nikitha Suresh - @marianikitha01

- Describe the goal of the project.

The goal of their project is to create a user-friendly shiny app that generates constellation maps to view the night sky from different locations based on the latitude and longitudinal point. 

- Describe the data used or collected.
The datasets are in GeoJSON (*.geojson) and GeoPackage (*.gpkg) formats, representing celestial objects' positions as of the J2000 epoch. They are roughly categorized into five sections: Asterisms, Constellations, DSOs (Deep-Sky Objects), Stars, and the Milky Way, each of them being further subdivided into subfiles.

- Describe how the research question will be answered, e.g. what approaches/methods will be used.
They are trying to make stargazing more engaging and educational by personalizing the experience through various elements: color usage, map location, time zone, and latitude/longitude location. 

- Is there anything that is unclear from the proposal?

Everything was clear except for the fact that they didn’t mention what they would be analyzing and if they would obtain any useful information about constellations.

- Provide constructive feedback on how the team might be able to improve their project.

Instead of just providing a link to access the dataset they should have explained more about the dataset. The information provided about the dataset is not enough to understand what the dataset contains. Also, explaining about the dataset in the proposal will save era reading of unnecessary information. 
The high-level goal should not be presented at the beginning. Starting with the goal without sharing detailed information about the topic or dataset can create confusion.
It would be nice if they could extend their goal to infer something about a particular constellation.

- What aspect of this project are you most interested in and would like to see highlighted in the presentation?
The approach they plan to use for visualization, involving entering longitude and latitude, is intriguing. I am eager to see if they can deliver on their promise of creating something highly interactive and innovative, as outlined in the proposal, rather than simply displaying straightforward plots for the constellations.

- Provide constructive feedback on any issues with file and/or code organization.

Including additional information about the dataset in the proposal would help us avoid the need to go through the entire source file to comprehend the data.
We feel that the start with the heading “ high-level goal” is a bit confusing. It should either come after the introduction of the data set or if not it should contain a small explanation about the topic.

- (Optional) Any further comments or feedback?

Overall, we think it is an amazing project and we are looking forward to your presentation.
Good luck, Chart Champions.

**Comment by KiwoonHong** [comment]
Thank you for your kind review! Good luck with your project!
