### ISSUE TITLE
Proposal feedback

### ISSUE THREAD

**Issue by Gchism94** [INFO526-DataViz/project-final-Chart-Champions#3]
Dear Chart Champions: Below is the score breakdown for your proposal. Details of things that should be updated/revised are provided in separate issues. As you address them, you should close the individual issues.

You can do this in one of two ways:

- On GitHub, by clicking on Close issue
- Via a commit that directly addresses the issue.

Please use the second method wherever a fix can be tied to a commit. If you preface your commit messages with "Fixes", "Fixed", "Fix", "Closed", or "Close", the issue will be closed when you push the changes to your repo. For example, suppose you want to close issue `#2` which, hypothetically, suggested that you add a new line to the README, your commit message can say something like `Add a new line to the README, closes #2`.

Once you've closed all of the other issues, close this one as well, so that going into the presentation you have no open issues remaining.

Your second score is **10/10**, so your final score is **9.25/10**

|          | Available | Earned |
|----------|-----------|--------|
| Data     | 3         |       3|
| Proposal | 5         |      5  |
| Workflow | 1         |        1|
| Teamwork | 1         |       1 |
| Total    | 10        |       10 |

**Feedback**: 
Data: I need to see the column types as well as the names. 
Proposal: I think you should have a few concrete objectives or outcome identified in bullets as well. 

Overall: the project is interesting and challenging. I like the reference app, so I will be interested to see what you come up with!

**Comment by meganhokama** [comment]
Hi Dr. Chism, 

Thank you for the helpful feedback! We have adjusted the proposal with the feedback you suggested. Hope you have a wonderful Thanksgiving break~

Best,
Chart Champions

**Comment by visalakshi2001** [comment]
Thank you for the regrade! 🎉
