### ISSUE TITLE
Presentation peer review

### ISSUE THREAD

**Issue by AkrantVarshney** [INFO526-DataViz/project-final-Chart-Champions#6]
The following is the peer review of the Presentation proposal by [name of team completing peer review]. The team members that participated in this review are 

- Akrant Varshney - @AkrantVarshney
- Hariharan Ramesh - @hari1016 
- Swetha Siripurapu - @SwethaSiripurapuu
- Maria Nikitha Suresh - @marianikitha01

- Content: Is the research question well designed and is the data being used relevant to the research question?

     Yes, everything was clear and the data used was completely connected to the research questions. 

- Content: Did the team use appropriate visualizations and did they interpret them accurately?

Yes the visualization was very impressive as it was clearly showing the constellations.  

- Creativity and Critical Thought: Is the project carefully thought out? Are the limitations carefully considered? Does it appear that time and effort went into the planning and implementation of the project?

The Data set chosen was not just huge but was very tricky still the team managed to make the best out of it they were successful in recreating the constellations on the plot in a very impressive ways they did faced some challenges but handled them very carefully. 

- Slides: Are the slides well organized, readable, not full of text, featuring figures with legible labels, legends, etc.?

The slides were organized but the slides were having too much text, they could have used relevant images which would have made the presentation much more interesting. 

- Professionalism: How well did the team present? Does the presentation appear to be well practiced? Are they reading off of a script? Did everyone get a chance to say something meaningful about the project?

Yes the presentation was well practiced and well presented in a professional way. No they were not reading off the script but yes they were reading few points from the slides as it is. 

The roles in the presentation was equally divided and every one presented the points which were not just important for the presentation but were also important for the project.

**Comment by visalakshi2001** [comment]
Thank you for the feedback, Team
