### ISSUE TITLE
Presentation peer review

### ISSUE THREAD

**Issue by Anshkumardev** [INFO526-DataViz/project-final-Chart-Champions#7]
The following is the peer review of the Presentation proposal by [name of team completing peer review]. The team members that participated in this review are 

Deema Albluwi (Computational Linguistics, PhD) - @Deec0dez
Rahul Bangad (Data Science, Master's) - @rahulbangad98
Swati Das (Data Science, Master's) - @Swati09Das
Ansh Kumar Dev (Data Science, Master's) - @Anshkumardev
Shakir Ahmed (Data Science, Master's)- @Shakir0585

- Content: Is the research question well designed and is the data being used relevant to the research question?

Research Question & Data Relevance:  The team has clearly defined the project's high-level goal, which is to develop a Shiny app for generating personalized constellation maps. The use of datasets like Milky Way, Constellation Lines, and Stars seems apt for the project. The data's relevance to the project's objective of increasing engagement and accessibility in astronomy is well-established.

- Content: Did the team use appropriate visualizations and did they interpret them accurately?

Visualizations & Interpretation: The presentation includes various visualizations like spherical maps and celestial datasets. These visual elements appear to be appropriately used to enhance the understanding of constellations. However, the presentation would benefit from a more detailed interpretation of these visualizations in relation to the research question.

- Creativity and Critical Thought: Is the project carefully thought out? Are the limitations carefully considered? Does it appear that time and effort went into the planning and implementation of the project?

Project Planning & Limitations: The project exhibits careful planning, especially in the approach to making astronomy accessible and engaging. The discussion of limitations, such as potential complexity in the app interface and issues with data accuracy, shows a thoughtful consideration of potential challenges.

Effort and Implementation: The detailed description of helper functions, plotting functions, and the final knitting together suggests significant time and effort in planning and implementation.

- Slides: Are the slides well organized, readable, not full of text, featuring figures with legible labels, legends, etc.?

Organization & Readability: The slides are well-organized, with clear sections delineating goals, datasets, analysis approach, and results. The text is concise, which aids readability. However, ensuring that all figures have legible labels and legends would further enhance the clarity of the visual content.

Design and Aesthetics: The slides' design, with appropriate backgrounds and color schemes, is visually appealing and aligns with the theme of constellations. The inclusion of code snippets adds an informative touch, although ensuring they are not too dense or complex for the audience is crucial.

- Professionalism: How well did the team present? Does the presentation appear to be well practiced? Are they reading off of a script? Did everyone get a chance to say something meaningful about the project?

Presentation Delivery: Based on the content, the team seems to have a good grasp of the subject. It would be beneficial to assess the actual delivery to comment on aspects like script reliance and practice.

Team Participation: The presentation appears to be a collaborative effort, as indicated by the inclusion of multiple authors. However, assessing whether each team member had a meaningful role would require observation of the actual presentation.

Overall Impression

The project demonstrates a commendable effort in making astronomy accessible through interactive visualization. The team has effectively utilized data and technology to create an educational tool, though there could be more emphasis on direct interpretation of visualizations. The presentation is visually engaging and well-structured, indicating thorough preparation and a professional approach.

**Comment by Anshkumardev** [comment]
Peer review updated

**Comment by visalakshi2001** [comment]
Thank you for the feedback, Team!
